create table tb_cliente (
    id bigint generated by default as identity (start with 1) not null primary key,
    codCliente text
);

create table tb_pedido (
    id bigint generated by default as identity (start with 1) not null primary key,
    numeroControle numeric,
    dataCadastro date,
    nomeProduto text,
    quantidadeProd numeric,
    codCliente text
);
