create table tb_cliente (
    id bigint generated by default as identity (start with 1) not null primary key,
    cod_cliente text
);

create table tb_pedido (
    id bigint generated by default as identity (start with 1) not null primary key,
    numero_controle numeric,
    data_cadastro date,
    nome_produto text,
    valor_uni_produto numeric,
    quantidade_prod numeric,
    cod_cliente text,
    valortotal numeric
);
